<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_dashboard   produk    baru</name>
   <tag></tag>
   <elementGuidId>9b74fd68-a6f9-450e-a56f-dcdaabd0de65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.chakra-heading.css-18j379d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b4784ef4-af54-4b08-80c9-e12792f1806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-heading css-18j379d</value>
      <webElementGuid>deb76e2f-1459-4f00-8605-0f8dfaf477e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dashboard  / produk   / baru</value>
      <webElementGuid>e27dd079-2d12-4e9a-9fe9-5b35adf1e64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-tyo1sz&quot;]/h2[@class=&quot;chakra-heading css-18j379d&quot;]</value>
      <webElementGuid>80a284f3-3d20-4700-8e2e-f19f82a8e0ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/h2</value>
      <webElementGuid>f46ad3c9-6e16-47a4-bde4-1a8a87ab87e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::h2[1]</value>
      <webElementGuid>822e5d58-f9d8-4cee-89eb-f2f178656905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tokoku'])[1]/following::h2[1]</value>
      <webElementGuid>68f7c95a-3129-413e-b62e-5cc4136dbe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/ baru']/parent::*</value>
      <webElementGuid>ef19a3e0-5ca0-485a-bb97-31d35a807017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>466da6d2-5748-4dd8-84a0-e8b2ff0e6c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'dashboard  / produk   / baru' or . = 'dashboard  / produk   / baru')]</value>
      <webElementGuid>d1331d3d-5dd7-4a65-acfd-ca3304717a19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
