<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Bahan Pokok</name>
   <tag></tag>
   <elementGuidId>aac1f9b5-dfd7-4508-a1d3-bd49d3e78abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Bahan Pokok' or . = 'Bahan Pokok')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-53']/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.css-u3dlpe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cf7fc09f-8940-4251-b486-dbfe3f623175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>bf44303e-cf84-49f5-811d-4c1bb5fc5235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-u3dlpe</value>
      <webElementGuid>2620a2be-b9f1-4d48-8bdc-89bf4382dd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahan Pokok</value>
      <webElementGuid>7883a2cf-eefd-4d2d-a043-636bf4e25bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-53&quot;)/table[@class=&quot;chakra-table css-fqy1u9&quot;]/tbody[@class=&quot;css-0&quot;]/tr[@class=&quot;css-13n66qk&quot;]/td[@class=&quot;css-u3dlpe&quot;]</value>
      <webElementGuid>8d5b5859-2b95-4dad-8e1d-fe2fff487ad2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-53']/table/tbody/tr/td</value>
      <webElementGuid>5c8daee5-0819-4ba7-bebf-4c0b1458fcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nama'])[2]/following::td[1]</value>
      <webElementGuid>3d585abb-2e89-4582-b666-d941ef2ab195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::td[1]</value>
      <webElementGuid>35e79908-d8a2-487b-b2b6-af68f4ad49ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[1]</value>
      <webElementGuid>1f529827-fa01-47ef-8717-b51c5036d273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::td[1]</value>
      <webElementGuid>549975bb-3445-4008-94bb-4bce20ef7e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bahan Pokok']/parent::*</value>
      <webElementGuid>f6f99345-466b-4831-93b9-53f465509574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>f136a9ad-a774-4cc1-aa9c-83dd0173607f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Bahan Pokok' or . = 'Bahan Pokok')]</value>
      <webElementGuid>a84cd124-99f4-49d2-b92e-89eae8005c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
