<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_produk</name>
   <tag></tag>
   <elementGuidId>d305f2ca-eedb-4713-bb64-e1f0d342373a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='chakra-modal--header-31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chakra-modal--header-31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>6efd3121-c2af-4961-99bd-514ea44aed8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__header css-9fgtzh</value>
      <webElementGuid>0ae00349-0726-4fb0-9f10-f57bd43a100e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--header-31</value>
      <webElementGuid>3f8806cc-ba0f-4a0c-8f76-aa98e700b530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>produk</value>
      <webElementGuid>4659b6bf-9629-4457-b4f9-c33071b5b483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--header-31&quot;)</value>
      <webElementGuid>9baadae8-5c0d-4788-bd9b-d977c8c30200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='chakra-modal--header-31']</value>
      <webElementGuid>f2057154-58ba-452c-abe7-48bd5276ca05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-31']/header</value>
      <webElementGuid>eaf943c8-9554-4b08-92da-c462b88ccbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'chakra-modal--header-31', '&quot;', ')')])[1]/following::header[1]</value>
      <webElementGuid>b039aabc-9108-4c6e-bd79-420e0f069d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::header[1]</value>
      <webElementGuid>0d7a4046-f3cb-4a15-a111-6c696e169f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kode'])[2]/preceding::header[1]</value>
      <webElementGuid>d7fd8737-4a8e-4d3f-9e79-a6e05b1835f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nama'])[2]/preceding::header[1]</value>
      <webElementGuid>2d54d659-d7b3-4d40-bd0f-b68230ee7e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>f3e0d584-45fb-47e9-9837-6855de22ebcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'chakra-modal--header-31' and (text() = 'produk' or . = 'produk')]</value>
      <webElementGuid>b27ffb98-a57d-4e79-b08f-3f393daa4a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
